In [1]:
l1=[1,2,3]
l2=[4,5,6]

In [2]:
l1+l2

[1, 2, 3, 4, 5, 6]

In [3]:
l2*2

[4, 5, 6, 4, 5, 6]

In [4]:
l1-l2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [2]:
import numpy as np

In [6]:
x=np.array(l1)
y=np.array(l2)
print(x)
y

[1 2 3]


array([4, 5, 6])

In [7]:
np.add(x,y)
#or
#x+y

array([5, 7, 9])

In [8]:
x-y

array([-3, -3, -3])

In [9]:
np.multiply(x,y)

array([ 4, 10, 18])

In [10]:
np.divide(x,y)

array([0.25, 0.4 , 0.5 ])

In [11]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

In [12]:
x+10

array([11, 12, 13])

In [13]:
x*2

array([2, 4, 6])

In [14]:
type(x)

numpy.ndarray

In [15]:
z=np.array([[1,2],[3,4],[5,6]])
print(z)
z

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
v=np.array([[1,2],[3,4],[5.1,6]]).reshape(2,3)
print(v)
print(type(v))
print(v.shape)
print(v.ndim)

[[1.  2.  3. ]
 [4.  5.1 6. ]]
<class 'numpy.ndarray'>
(2, 3)
2


In [17]:
# Dimension
print(x.shape)
z.shape

(3,)


(3, 2)

In [18]:
print(x.ndim)
print(y.ndim)
z.ndim

1
1


2

In [19]:
print(x.dtype)
print(y.dtype)
v.dtype

int64
int64


dtype('float64')

In [20]:
#Matrix Creation
#Method 1
l3=[[1,2,3],[4,5,6],[7,8,9]]
print(l3)
l4=["a","b","c","d"]
a4=np.array(l4)
print(a4)
print(a4.shape)
print(a4.ndim)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
['a' 'b' 'c' 'd']
(4,)
1


In [21]:
l=np.array(l3).reshape(3,3)
print(l)
type(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [22]:
s=np.array(l4).reshape(2,2)
s

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [23]:
s.shape

(2, 2)

In [24]:
s.ndim

2

In [25]:
si=np.matrix(a4)

In [26]:
si.shape

(1, 4)

In [27]:
si.ndim

2

In [28]:
si

matrix([['a', 'b', 'c', 'd']], dtype='<U1')

In [29]:
print(si.reshape(2,2))

[['a' 'b']
 ['c' 'd']]


In [30]:
l5=[[1,2,3],[4,5,6],[7,8]]
t=np.matrix(l5)
print(t)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [31]:
l5=[[1,2,],[4,5,],[7,8]]
t=np.matrix(l5).reshape(2,3)
print(t)

[[1 2 4]
 [5 7 8]]


In [32]:
i=np.eye(3)# Identity Matrix eye(),zeros(),ones(),sqrt(),divide(),linalg.det() the default is float
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((2,4),dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.ones((2,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
np.eye(3,dtype=np.int64)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
#arange()
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [40]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
#Indexing and Slicing
p=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(p)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
p[[0,1,2],[0,1,0]]

array([1, 6, 9])

In [6]:
np.array([p[0,0],p[1,1],p[2,0]])

array([1, 6, 9])

In [44]:
print(p[0][1])
p[0][1]

2


np.int64(2)

In [45]:
# p[row,col]
p[:1,:2]

array([[1, 2]])

In [46]:
p[:1,:1]

array([[1]])

In [47]:
np.array([p[0,0],p[1,1]])

array([1, 6])

In [48]:
np.array(p[[0,1,2],[0,1,0]])

array([1, 6, 9])

In [49]:
p[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [50]:
p[1::2,1::2]

array([[6, 8]])

In [51]:
p[0::2,0:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [52]:
p[0::2,0::2]

array([[ 1,  3],
       [ 9, 11]])

In [53]:
p[::-1,::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [54]:
#Boolean Array Indexing
q=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(q)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
m=q>4
print(q)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [56]:
#Vectorization
aq=q[q>4]
print(aq)

[ 5  6  7  8  9 10 11 12]


In [57]:
np.trace(q)#Sum of Diagonals

np.int64(18)

In [58]:
np.linalg.det([[1,2],[3,4]])

np.float64(-2.0000000000000004)

In [59]:
np.linalg.det([[1,2,3],[4,5,6],[7,8,9]])

np.float64(6.66133814775094e-16)

In [60]:
a=[[1,2,3],[4,5,6]]
b=[[7,8,9],[10,11,12]]
ta=np.array(a)
tb=np.array(b)
print(ta)
print(tb)
ta+tb

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 8, 10, 12],
       [14, 16, 18]])

In [61]:
tb-ta

array([[6, 6, 6],
       [6, 6, 6]])

In [62]:
np.multiply(ta,tb)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [63]:
np.divide(ta,tb)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [64]:
np.sqrt(ta)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [65]:
np.sqrt(tb)

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [66]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[11,12,13],[14,15,16],[17,18,19]]

In [67]:
na=np.array(a)
nb=np.array(b)
print(na)
print(nb)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [68]:
#Axes Notation,x=0 means adds the col values
print(na.sum(axis=0))
print(nb.sum(axis=0))

[12 15 18]
[42 45 48]


In [69]:
#Axes Notation,x=1 means adds the row values
print(na.sum(axis=1))
print(nb.sum(axis=1))

[ 6 15 24]
[36 45 54]


In [70]:
np.max(na)

np.int64(9)

In [71]:
np.min(na)

np.int64(1)

In [72]:
np.median(na)

np.float64(5.0)

In [73]:
na.dtype

dtype('int64')

In [74]:
np.mean(na)

np.float64(5.0)

In [75]:
#Broadcasting
na

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
na+np.arange(3)

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [78]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.zeros((2,3)).reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [81]:
np.zeros((2,3)).reshape(3,2)+1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [82]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [83]:
np.arange(4).reshape(4,1)+np.arange(4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [84]:
np.arange(4)+7

array([ 7,  8,  9, 10])