In [1]:
import numpy as np

In [3]:
data_file=r"E:\CSV files\makeSenseOfCensus.csv"

In [4]:
data=np.genfromtxt(data_file,delimiter=",",skip_header=1)
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]], shape=(1000, 8))

In [5]:
data.shape

(1000, 8)

In [6]:
type(data)

numpy.ndarray

In [7]:
data.ndim

2

In [15]:
#Append The data
d=[[60,15,0,1,0,0,36,1]]
new_data=np.concatenate((data,d),axis=0)
print(new_data)
print(new_data.shape)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [60. 15.  0. ...  0. 36.  1.]]
(1001, 8)


In [16]:
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]], shape=(1000, 8))

In [18]:
print(type(new_data))
new_data

<class 'numpy.ndarray'>


array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [60., 15.,  0., ...,  0., 36.,  1.]], shape=(1001, 8))

In [21]:
#Max age
age=new_data[:,0]
max_age=np.max(age) #age.max()
max_age

np.float64(90.0)

In [22]:
#Min age
min_age=age.min()
min_age

np.float64(17.0)

In [23]:
#Mean age
mean_age=np.mean(age)
mean_age

np.float64(38.07292707292707)

In [24]:
senior_citizen=age[age>60]
senior_citizen

array([79., 67., 76., 61., 70., 64., 71., 68., 66., 64., 90., 66., 75.,
       65., 64., 61., 65., 77., 62., 76., 63., 66., 67., 65., 62., 63.,
       80., 67., 63., 72., 62., 74., 67., 72., 69., 65., 65., 71., 70.,
       66., 65., 61., 61., 68., 64., 64., 62., 73., 72., 63., 62., 61.,
       71., 63., 63., 67., 81., 64., 67., 78., 63.])

In [25]:
age>60

array([False, False, False, ..., False, False, False], shape=(1001,))

In [26]:
working_hrs=new_data[:,6]
avg_hrs=np.mean(working_hrs[age>60])
print(avg_hrs)

31.42622950819672


In [27]:
tot_working_hrs=np.sum(working_hrs[age>60])
tot_working_hrs

np.float64(1917.0)

In [28]:
num_sc=len(senior_citizen)
num_sc

61

In [29]:
avg_hrs_using_sum_func=tot_working_hrs/num_sc
avg_hrs_using_sum_func

np.float64(31.42622950819672)

In [30]:
if avg_hrs>25:
    print("Not follows the govt policy")
else:
    print("Follows the govt policy")

Not follows the govt policy


In [32]:
edu_num=new_data[:,1]
high=edu_num[edu_num>10]
low=edu_num[edu_num<=10]
print(len(high))
print(len(low))

328
673


In [33]:
income=new_data[:,7]
avg_high_income=np.mean(income[edu_num>10])
avg_low_income=np.mean(income[edu_num<=10])
print(avg_high_income)
print(avg_low_income)

0.4298780487804878
0.13670133729569092


In [34]:
if avg_high_income>avg_low_income:
    print("Higher educated people have better general pay")
else:
    print("Higher people doesn't have the better general pay")

Higher educated people have better general pay
