### Numpy Project

In [1]:
import numpy as np

In [2]:
#Load the data. Data is already given to you in variable path
data_file=r"E:\CSV files\KAG_Conversion_Data.csv"

In [7]:
data_str=np.genfromtxt(data_file,delimiter=",",skip_header=1,dtype="str")
data_float=np.genfromtxt(data_file,delimiter=",",skip_header=1,dtype="float")
data_int=np.genfromtxt(data_file,delimiter=",",skip_header=1,dtype="int")

In [8]:
data_str

array([['708746', '916', '103916', ..., '1.429999948', '2', '1'],
       ['708749', '916', '103917', ..., '1.820000023', '2', '0'],
       ['708771', '916', '103920', ..., '0', '1', '0'],
       ...,
       ['1314412', '1178', '179979', ..., '40.28999949', '2', '0'],
       ['1314414', '1178', '179981', ..., '198.7100005', '8', '2'],
       ['1314415', '1178', '179982', ..., '165.6099987', '5', '2']],
      shape=(1143, 11), dtype='<U11')

In [9]:
data_float

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]], shape=(1143, 11))

In [10]:
data_int

array([[ 708746,     916,  103916, ...,      -1,       2,       1],
       [ 708749,     916,  103917, ...,      -1,       2,       0],
       [ 708771,     916,  103920, ...,       0,       1,       0],
       ...,
       [1314412,    1178,  179979, ...,      -1,       2,       0],
       [1314414,    1178,  179981, ...,      -1,       8,       2],
       [1314415,    1178,  179982, ...,      -1,       5,       2]],
      shape=(1143, 11))

In [18]:
#How many unique ad campaigns (xyzcampaignid) does this data contain ? And for how many times was each campaign run ?
xyzid=data_str[:,1]
tot_xyz_c_id=np.unique(xyzid)
print(tot_xyz_c_id)

['1178' '916' '936']


In [30]:
tot_xyz_c_id,count = np.unique(xyzid, return_counts = True)
print(tot_xyz_c_id)
print(count)
# tot_xyzid=np.unique_counts(xyzid)
# print(tot_xyzid.values)
# print(tot_xyzid.counts)

['1178' '916' '936']
[625  54 464]


In [21]:
for i in range(len(count)):
    print(f'The campaign id of {tot_xyz_c_id[i]} ran for {count[i]} times')

The campaign id of 1178 ran for 625 times
The campaign id of 916 ran for 54 times
The campaign id of 936 ran for 464 times


In [31]:
#What are the age groups that were targeted through these ad campaigns?
age=data_str[:,3]
age_group=np.unique(age)
print(age_group)

['30-34' '35-39' '40-44' '45-49']


In [36]:
#What was the average, minimum and maximum amount spent on the ads?
amount_spent=data_float[:,8]
max_spent=amount_spent.max()
min_spent=amount_spent.min()
avg_spent=amount_spent.mean()
print("Maximum amount spent:",max_spent)
print("Minimum amount spent:",min_spent)
print("Average amount spent:",avg_spent)

Maximum amount spent: 639.9499981
Minimum amount spent: 0.0
Average amount spent: 51.36065613141295


In [37]:
#What is the id of the ad having the maximum number of clicks ?
clicks=data_float[:,7]
max_clicks=np.max(clicks)
print(max_clicks)

421.0


In [40]:
ad_id=data_float[:,0]
#print(ad_id[int(max_clicks)])
print("Maximum no of clicks ad id:",ad_id[clicks==max_clicks])

Maximum no of clicks ad id: [1121814.]


In [48]:
#How many people bought the product after seeing the ad with most clicks? Is that the maximum number of purchases in this dataset?
appr_con=data_float[:,10]
tot_appr_con=appr_con[clicks==max_clicks]
max_app_con=appr_con.max()
if tot_appr_con>max_app_con:
    print("It's the maximum no:of purchase")
else:
    print("It's not the maximum purchase in the dataset")
print(max_app_con)
print(tot_appr_con)

It's not the maximum purchase in the dataset
21.0
[13.]


In [45]:
#So the ad with the most clicks didn't fetch the maximum number of purchases. Find the details of the product having maximum number of purchases
max_appr_con=np.max(appr_con)
print(max_appr_con)

21.0


In [46]:
fb_id=data_float[:,2]
print(f'The Maximum no:of purchases product details:\nThe ad_id:{ad_id[appr_con==max_appr_con]}\nThe xyz_campaign_id:{xyzid[appr_con==max_appr_con]}\nThe fb_campaign_id:{fb_id[appr_con==max_appr_con]}')

The Maximum no:of purchases product details:
The ad_id:[1121104.]
The xyz_campaign_id:['1178']
The fb_campaign_id:[144533.]
